version: "3.7"
services:
  pulsar:
    image: apachepulsar/pulsar-all:2.5.0
    environment:
      - PULSAR_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"
    volumes:
      - "/pulsar/data"
      - "/pulsar/conf"
      - "./engine/build/libs:/zenaton/engine/build:delegated"
      - "./engine:/zenaton/engine"
    ports:
      - "6650:6650"
      - "8080:8080"
